-- https://school.programmers.co.kr/learn/courses/30/lessons/299308

SELECT CASE WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) < 7 THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) < 10 THEN '3Q'
        ELSE '4Q' END AS QUARTER, 
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER

-- CASE 대신 CONCAT(CEIL(MONTH(DIFFERENTIATION_DATE) / 3), 'Q') 이용가능